blogs:
  unixpickle: https://blog.aqnichol.com/
  scotthyoung: https://www.scotthyoung.com/blog/
  waitbutwhy: https://waitbutwhy.com/
  kencaldeira: https://kencaldeira.wordpress.com/
  samaltman: http://blog.samaltman.com/

internships:
  github: https://github.com/about/careers#internships
  tesla: https://www.tesla.com/en_CA/careers/search#/?keyword=intern
  google: https://careers.google.com/jobs#t=sq&q=j&li=20&l=false&jlo=en-US&jc=TECHNICAL_WRITING&jc=SOFTWARE_ENGINEERING&jc=USER_EXPERIENCE&je=INTERN&jcoid=7c8c6665-81cf-4e11-8fc9-ec1d6a69120c&jcoid=e43afd0d-d215-45db-a154-5386c9036525&jcoid=4ce051e9-0861-4457-ae74-ed29d709e6d9&jcoid=db402fa7-80f9-417e-90f8-cabc095ab328&jcoid=4da87eaf-2d83-4e44-aec5-3277162353f3&jcoid=368ee4a3-8f63-4554-b52c-8c5ad137a48a&jcoid=8e95bc8e-bc66-4a8f-a30c-4be6e037beab&jcoid=65a96848-6a90-403f-b350-76dcbf787382&jcoid=7143c4f4-17a1-4061-a066-69aafca4467b&
  dropbox: https://www.dropbox.com/jobs/teams/eng_university_grads#open-positions
  paypal: https://www.paypal.com/ca/webapps/mpp/jobs/students-and-grads/undergraduate-internships-close#
  facebook: https://www.facebook.com/careers/university/internships/engineering
